### ISSUE TITLE
change from true highlighter to rogue highlighter

### ISSUE THREAD

**Issue by matyikriszta** [codebar/manual#25]
Per this build warning:

> The page build completed successfully, but returned the following warning:
> You are attempting to use the 'true' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

Steps to fix this build warning are in this blog post by Github:
https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

**Comment by jwithington** [comment]
Hey hey -- I found this help-wanted issue because I was looking around at open source open issues.  It doesn't look like it's an issue any more, so you might want to close it so more newbies don't think they could help out! 😄 

Cheers! 🍻
