### ISSUE TITLE
Investigate CNAME already taken page build warning

### ISSUE THREAD

**Issue by matyikriszta** [codebar/manual#26]
Per this page build warning:

> The page build completed successfully, but returned the following warning:
> CNAME already taken: manual.codebar.io. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.
> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by despo** [comment]
I think I've seen this before and it's due to a fork gh-pages build failing - so not primary repo with CNAME. Not an issue.
