### ISSUE TITLE
Add social media guidelines.

### ISSUE THREAD

**Issue by despo** [codebar/manual#51]

**Comment by KimberleyCook** [comment]
I'm very much on board with this. I just added an issue in the chapter org meeting repo so we can discuss it with other organisers at the next meetup. https://github.com/codebar/chapter-organiser-meetings/issues/12

**Comment by matyikriszta** [comment]
@despo @KimberleyCook I'm in the process of moving all the content from here over to the new docs repo, I'm going to close this issue and open one on that repo.
