### ISSUE TITLE
Recommended gender neutral bathroom sign implies wheelchair accessibility

### ISSUE THREAD

**Issue by biggianteye** [codebar/manual#53]
The host guide document recommends a gender neutral bathroom sign for people to put up on the day. This is great, but the chosen sign has a wheelchair symbol on it implying the toilet will also be wheelchair accessible which may be misleading and conflates two different issues (gender neutrality and accessibility). For example, my current office has bathrooms that are suitable for all genders but are not wheelchair accessible, so this sign would not be suitable.

http://www.uua.org/sites/live-new.uua.org/files/documents/lgbtq/gender_neutral_bathroom_11x17.pdf
![image](https://user-images.githubusercontent.com/1482649/64914894-c857d400-d752-11e9-8ec0-85b43c0d1e9e.png)

It would be good to suggest an alternative which doesn't have a wheelchair symbol, either as a replacement or a companion to the existing sign.

**Comment by biggianteye** [comment]
It's also linked from the organiser guide.

**Comment by matyikriszta** [comment]
@biggianteye how about the non accessible version on this page? https://www.refugerestrooms.org/signs

Or I quiet like this one too, my only issue it being completely black so a bit resource intense to print
http://www.guidetogender.com/toilet/

**Comment by biggianteye** [comment]
> @biggianteye how about the non accessible version on this page? https://www.refugerestrooms.org/signs

This one solves the problem I pointed out. It's a shame it uses the dress motif rather than the generic human that the current one does. 🤷‍♂ 

> Or I quiet like this one too, my only issue it being completely black so a bit resource intense to print
> http://www.guidetogender.com/toilet/

I like this too, but agree with what you say. An inverted version of this might be good but given we just want to point to an existing resource, the first one looks like a better option.

**Comment by matyikriszta** [comment]
@biggianteye excellent, I'll open a PR to replace the current image with the first option.

**Comment by matyikriszta** [comment]
And here it is @biggianteye if you'd like to review it: https://github.com/codebar/manual/pull/55.
