### ISSUE TITLE
create codebar leaflet

### ISSUE THREAD

**Issue by despo** [codebar/manual#9]
This is a place to collect content on the leaflet we want to create.

The leaflet will be distributed to all codebars and has induction information for both students and coaches.

**Comment by despo** [comment]
- [ ] The leaflet should contain information for both coaches and students - to encourage transparency
- [ ] Utilise illustrations
- [ ] have a look at 'what is codebar'
- [ ] include full CoC or short version?

**Comment by KimberleyCook** [comment]
This has been created, closing the issue.
